---
- name: Install MariaDB and Utils on Debian OS Family (based on your choice in icinga2_web_ui_ido value)
  apt: name={{ item.package }}
       state=latest
  with_items: icinga2_web_ui_mariadb_deb
  when: ansible_distribution_major_version == "8"

- name: Install MySQL and Utils on Debian OS Family (based on your choice in icinga2_web_ui_ido value)
  apt: name={{ item.package }}
       state=latest
  with_items: icinga2_web_ui_{{ icinga2_web_ui_ido }}_deb
  when: ansible_distribution_major_version == "7"

- name: Start MySQL
  service: name=mysql state=started enabled=yes

- name: Create a Database for Icinga
  mysql_db: name=icinga state=present
  register: icinga_db

- name: Import IDO Schema on Icinga Database (only once)
  mysql_db: name=icinga
            state=import
            target={{ icinga2_ido_mysql_schema_deb }}
  when: icinga_db.changed == true

- name: Create Icinga Database User and configure Grants
  mysql_user: name=icinga
              password=icinga
              state=present
              priv="icinga.*:GRANT,INSERT,SELECT,UPDATE,DELETE,DROP,CREATE VIEW,INDEX,EXECUTE"

- name: Configure Icinga2 Ido Mysql Feature
  template: src=ido-mysql.conf.j2
            dest={{ icinga2_ido_mysql_conf }}
            backup=no
            owner=nagios
            group=nagios
            mode=0640
