---

- name: Install PostgreSQL on Debian OS Family
  apt: pkg=postgresql
       state=latest

- name: Start PostgreSQL server
  service: name=postgresql
           state=started
           enabled=yes

- name: Create a Database for Icinga
  pssql_db: name={{ icinga2_web_db_dbuser }}
            state=present
  register: icinga_db

- name: Create Icinga Database User and configure Grants
  pssql_user: name={{ icinga2_web_db_dbuser }}
              password={{ icinga2_web_db_dbuser }}
              state=present
              priv="{{ icinga2_web_db_dbuser }}.*:GRANT,INSERT,SELECT,UPDATE,DELETE,DROP,CREATE VIEW,INDEX,EXECUTE"

- name: Import IDO Schema on Icinga Database (only once)
  pgsql_db: name=icinga
            state=import
            target={{ icinga2_ido_pgsql_schema }}
  when: icinga_db.changed == true

- name: Configure Icinga2 Ido pgsql Feature
  template: src=ido-pgsql.conf.j2
            dest={{ icinga2_ido_pgsql_conf }}
            backup=no
            owner={{ icinga2_web_db_dbuser }}
            group={{ icinga2_web_db_dbuser }}
            mode=0640

- name: Configure pg_hba.conf
  template: src=pg_hba.conf
  dest={{ Icinga2_pg_hba_conf }}

- name: Enable Icinga2 Ido pgsql Feature
  command: "icinga2 feature enable ido-{{ icinga2_web_ui_ido }}"
  register: features_result
  changed_when: "'for these changes to take effect' in features_result.stdout"
  notify:
   - restart icinga2
