---
- name: Add icinga web 2 PPA signing key
  apt_key: url=http://packages.icinga.org/icinga.key state=present

- name: Adds icinga web 2 PPA
  apt_repository: repo='deb http://packages.icinga.org/ubuntu icinga-{{ansible_distribution_release}} main'

- name: Install IDO {{ icinga2_web_ui_ido }} on Debian OS family
  apt: pkg=icinga2-ido-{{ icinga2_web_ui_ido }}
       update_cache=yes
       state=latest
       install_recommends=no

- include: icinga2_web_ui_pgsql_Debian_install.yml
  when: icinga2_web_ui_ido == "pgsql"

- name: Install Icinga Web on Debian OS family
  apt: pkg=icingaweb2
       state=latest
       install_recommends=no

- name: Install Apache configuration
  template: src=icingaweb2.conf
            dest=/etc/apache2/sites-enabled/icingaweb2.conf
            backup=no

- name: Install Apache
  apt: pkg={{ item }}
       state=latest
       install_recommends=no
  with_items:
  - apache2
  - libapache2-mod-php5

- name: Symlink Icinga workaround
  file: src=/usr/share/php/Icinga
        dest=/usr/share/icingaweb2/public/Icinga
        state=link

- name: Start Apache
  service: name=apache2
           state=started
           enabled=yes

- name: UI Installation finished (RH)
  debug: msg="{{ icinga2_web_ui_ido }}"

- name: Icinga Web UI Installation finished (RH)
  debug: msg="Login at https://icinga2.badpacket.in with user root and password password"
