---
- name: Copy Main Icinga2 Configuration
  template: src=icinga2.conf.j2
            dest={{ icinga2_main_conf }}
            backup=yes
            owner=root
            group=root
            mode=0644
  notify:
   - restart icinga2

- name: Enable features
  command: icinga2 feature enable {{item}}
  register: features_result
  changed_when: "'for these changes to take effect' in features_result.stdout"
  with_items: icinga2_features
  notify:
    - restart icinga2

- name: Copy Check Commands Configuration
  template: src=icinga2_check_commands.j2
            dest={{ icinga2_conf_d }}/check_commands.conf
            backup=yes
            owner=root
            group=root
            mode=0644
  notify:
   - restart icinga2

- name: Copy Zones Configuration
  template: src=icinga2_zones.conf.j2
            dest={{ icinga2_zones_conf }}
            backup=yes
            owner=root
            group=root
            mode=0644
  notify:
   - restart icinga2
